#!/usr/bin/env python3

import os
import fnmatch

from jinja2 import Environment
from jinja2.exceptions import TemplateSyntaxError

errors = 0

env = Environment()

for root, dirs, files in os.walk("."):
    for name in files:
        if fnmatch.fnmatch(name, "*.j2"):
            f = os.path.join(root, name)
            with open(f) as template:
                try:
                    env.parse(template.read())
                except TemplateSyntaxError as e:
                    print(f"Error parsing {f}: {e}")
                    errors += 1

exit(errors)

# vim: set ft=python :
